### ISSUE TITLE
Add & CI-enforce MiMa

### ISSUE THREAD

**Issue by dwijnand** [lightbend/sbt-whitesource#24]
I noticed that this is missing.

**Comment by raboof** [comment]
I'm not sure I'd care since an sbt plugin is rarely a transitive dependency, but ofc no objection either.

**Comment by dwijnand** [comment]
Mostly I'm interested in not breaking backwards compatibility, so MiMa will ensure that by enforcing the binary API.

But WRT transitive dependencies, having an sbt plugin to bring in other plugins is fairly common (sbt/sbt-houserules, playframework/interplay, scala/sbt-scala-module).
