### ISSUE TITLE
Drop some log config tips in the README

### ISSUE THREAD

**Issue by dwijnand** [lightbend/sbt-whitesource#42]
See https://hc.apache.org/httpcomponents-client-ga/logging.html

**Comment by patrick-premont** [comment]
The whitesource library relies on the Apache `httpclient`. We can configure its logging as described here: https://hc.apache.org/httpcomponents-client-ga/logging.html

Passing these options to sbt shows the requests and responses:

```
-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog
-Dorg.apache.commons.logging.simplelog.showdatetime=true
-Dorg.apache.commons.logging.simplelog.log.org.apache.http=DEBUG
```
