### ISSUE TITLE
whitesourceIgnoreTestScopeDependencies is ignored

### ISSUE THREAD

**Issue by dwijnand** [lightbend/sbt-whitesource#48]
_Originally posted by @dwijnand in https://github.com/lightbend/sbt-whitesource/issues/8#issuecomment-436341940_

There's a `whitesourceIgnoreTestScopeDependencies` which defaults to `true`, but it looks like it isn't used.

In order to fix this bug one would need to compare this plugin with the maven plugin and figure out where this plugin isn't using that key.  (This plugin is a port of the maven plugin, so things should look similar.)

**Comment by raboof** [comment]
It's used at https://github.com/lightbend/sbt-whitesource/blob/93f2857f0c103015f2e0061da91d1a09ae7c399c/src/main/scala/sbtwhitesource/WhiteSourcePlugin.scala#L189, right? (IIRC we have JMH, which is GPL, as a test dependency in Akka and it (correctly) doesn't show up in the report)

**Comment by dwijnand** [comment]
I'm not sure about JMH, but that line just populates:

https://github.com/lightbend/sbt-whitesource/blob/bbc00cc655d6d2b0937f02319efbf2ef1d2fc5f2/src/main/scala/sbtwhitesource/WhiteSource.scala#L42

which is then unused.

**Comment by raboof** [comment]
Doh, sorry
