### ISSUE TITLE
Proposal: filter out non-published projects by default

### ISSUE THREAD

**Issue by TimMoore** [lightbend/sbt-whitesource#53]
I want to start a discussion about whether it makes sense to have WhiteSource reports for sub-projects that don't publish artifacts, such as testing projects, benchmarks, etc.

Could the plugin exclude these by default?

**Comment by dwijnand** [comment]
Sure!

**Comment by eed3si9n** [comment]
It would be nice if `publish / skip` would skip WhiteSource.
